### ISSUE TITLE
添加手势

### ISSUE THREAD

**Issue by dslcoding** [wangyingbo/YBTableHeaderAnimationDemo#2]
我给_titleLabel和_subTitleLabel添加手势，_titleLabel.userInteractionEnabled = YES;都打开了，也没有反应。但是_userLogoImageView添加手势是可以 。我很郁闷。不知道是怎么回事

**Comment by wangyingbo** [comment]
<img width="940" alt="1" src="https://user-images.githubusercontent.com/12741589/43440049-6364bdce-94c8-11e8-8e6a-50e649ac7772.png">
这里判断了fu父控件的第一响应者的响应范围，把这里的代码注释掉就OK了，最新代码提交里已经修改过了
@dslcoding

**Comment by dslcoding** [comment]
非常感谢

**Comment by wangyingbo** [comment]
fix it
