### ISSUE TITLE
#define kUSER_INFO_HEADERVIEW_H 180 不能修改吗？

### ISSUE THREAD

**Issue by dslcoding** [wangyingbo/YBTableHeaderAnimationDemo#3]
#define kUSER_INFO_HEADERVIEW_H 180 我想修改这个数值。为什么一修改下拉动画就没有了？

**Comment by wangyingbo** [comment]
可以修改的，不过还有常量值需要修改
![image](https://user-images.githubusercontent.com/12741589/43686597-2dd0892c-98fb-11e8-8383-4ad7e7d50287.png)
修改的时候要保证kUSER_INFO_HEADERVIEW_H小于kMaxScrollContentSizeY，比如#define kUSER_INFO_HEADERVIEW_H 250，就要修改kMaxScrollContentSizeY大于250

@dslcoding

**Comment by wangyingbo** [comment]
你好，解决了此bug，提交了代码。可任意修改宏定义kUSER_INFO_HEADERVIEW_H的值和常量下拉最大值kMaxScrollContentSizeY的值，请下载最新的代码。谢谢反馈。
<img width="532" alt="2018-08-05 11 28 56" src="https://user-images.githubusercontent.com/12741589/43687461-0b4ee27e-9908-11e8-80d1-ab16e4d7d094.png">
<img width="532" alt="2018-08-05 11 29 11" src="https://user-images.githubusercontent.com/12741589/43687462-0ea8be0e-9908-11e8-840f-3fd97d58c433.png">

@dslcoding

**Comment by wangyingbo** [comment]
@dslcoding 优化了下拉圆弧时的代码，更加简洁一些。
